#!/usr/bin/env python3
"""Regenerate unicode_ln.h: the code point ranges above ASCII that are letters (\\p{L}) and numbers (\\p{N}),
for pretok_qwen2.h. Python's unicodedata is the source; the Unicode version is written into the header.

    python firmware/bench-one/shared/make_unicode_tables.py

White_Space code points are left out of both tables, because llama.cpp classifies whitespace first and the
pre-tokenizer does the same (a code point is whitespace, letter, number or other -- exactly one)."""
import os
import unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))
WS = {0x85, 0xA0, 0x1680, 0x2028, 0x2029, 0x202F, 0x205F, 0x3000} | set(range(0x2000, 0x200B))


def ranges(prefix):
    out, start = [], None
    for cp in range(0x80, 0x110000):
        ok = cp not in WS and unicodedata.category(chr(cp)).startswith(prefix)
        if ok and start is None:
            start = cp
        if not ok and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def emit(name, rs):
    lines = ["static const uint32_t %s[%d][2] PT_CONST = {" % (name, len(rs))]
    row = []
    for a, b in rs:
        row.append("{0x%X,0x%X}," % (a, b))
        if len(row) == 6:
            lines.append("    " + " ".join(row))
            row = []
    if row:
        lines.append("    " + " ".join(row))
    lines.append("};")
    return "\n".join(lines)


L, N = ranges("L"), ranges("N")
text = """/* GENERATED by make_unicode_tables.py from Python's unicodedata (Unicode %s) -- do not edit.
 * Code point ranges above 0x7F: letters (general category L*) and numbers (N*), White_Space excluded.
 * %d + %d ranges, %d bytes. On the Teensy they stay in flash (a plain const array on a Teensy 4 is copied
 * into RAM1, which is the stack's). */
#ifndef UNICODE_LN_H
#define UNICODE_LN_H
#include <stdint.h>
#if defined(__IMXRT1062__)
  #define PT_CONST __attribute__((section(".progmem")))
#else
  #define PT_CONST
#endif
%s
%s
#endif
""" % (unicodedata.unidata_version, len(L), len(N), 8 * (len(L) + len(N)), emit("UNI_L", L), emit("UNI_N", N))
open(os.path.join(HERE, "unicode_ln.h"), "w", encoding="utf-8", newline="\n").write(text)
print("unicode_ln.h: %d letter ranges, %d number ranges, Unicode %s" % (len(L), len(N), unicodedata.unidata_version))
