#!/usr/bin/env python3
"""make_tests_v7.py -- write tests_v7.txt: an A/B of how the card is read, then the night-2 tests.

    python make_tests_v7.py

v7 reads the card by DMA while the arithmetic runs. Four switches move only the time (the step lines must stay
identical): ::sdio fifo|dma, ::overlap 0|1, ::align 0|1 (whole sectors per read, one card command) and
::slice N (rows per yield: 0 = one row, N = N us of rows). The same short France run (a 5-position batched
pass and two one-position passes) goes through the default and then through each switch changed ALONE, so
each difference in the pass lines belongs to one switch; suite.py checks the five print identical step lines.
Then the card goes back to the default and the night-2 tests run as before, and a second group of 8
(together8b) asks what the first does not: two facts, a subtraction, C and Arduino code, a bug to find, an
explanation, and a yes/no with a reason (from survey2_prompts.txt, answered on the PC in bench-archive/
20260927-090924-psram_llm-survey). Chat prompts go through the model's own template, as in night 2."""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from chat_template import escape, render  # noqa: E402

GEN = 16
PLAIN_B = [("moon", "The first person to walk on the Moon was"),
           ("dna", "DNA stands for"),
           ("sub", "Q: What is 1000 - 358?\nA:"),
           ("c_printf", '#include <stdio.h>\nint main(void) {\n    printf("'),
           ("blink", "// Toggle an LED on pin 13 every second\nvoid setup() {\n")]
CHAT_B = [("bug", "Find the bug:\ndef add(a, b):\n    return a - b"),
          ("spi_i2c", "What is the difference between SPI and I2C? Answer in two sentences."),
          ("prime91", "Is 91 a prime number? Answer yes or no, then why.")]


def main():
    night2 = [s.rstrip("\n") for s in open(os.path.join(HERE, "tests_night2.txt"), encoding="utf-8")]
    body = [s for s in night2 if not s.startswith("#")]
    lines = ["# psram_llm v7 suite -- GENERATED by make_tests_v7.py; edit that, not this.",
             "# 1. the card-read A/B on one build: the default, then slice, align, overlap and FIFO each changed alone",
             "# 2. the night-2 tests (see make_tests_night2.py for the margins and projections)",
             "::prefill 1",
             "::sdio dma", "::overlap 1", "::align 1", "::slice 0",
             "ab_default | 2 | The capital of France is",
             "::slice 200",
             "ab_slice200 | 2 | The capital of France is",
             "::slice 0", "::align 0",
             "ab_unaligned | 2 | The capital of France is",
             "::align 1", "::overlap 0",
             "ab_no_overlap | 2 | The capital of France is",
             "::overlap 1", "::sdio fifo",
             "ab_fifo | 2 | The capital of France is",
             # the rest in FIFO: v7b's ::bench measured DMA_SDIO at 7.26 MB/s against FIFO's 18.5, same 49.5 MHz
             # clock, every read size, OCRAM and DTCM alike -- a pass's 1.83 GB alone would take 253 s by DMA
             "# the tests below run in FIFO: ::bench measured DMA_SDIO at 7.26 MB/s and FIFO at 18.5 on this card",
             "::sdio fifo"] + body
    lines += ["# 3. a second group of 8, different kinds of question",
              "::prefill 1",
              "@multi together8b | %d" % GEN]
    lines += ["%s | %s" % (i, escape(p)) for i, p in PLAIN_B]
    lines += ["%s | %s" % (i, escape(render(u))) for i, u in CHAT_B]
    lines.append("@end")
    with open(os.path.join(HERE, "tests_v7.txt"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("tests_v7.txt: %d lines" % len(lines))


if __name__ == "__main__":
    main()
