#!/usr/bin/env python3
"""make_tests_realistic.py -- write tests_realistic.txt: one real chat request, timed the way a user feels it.

    python make_tests_realistic.py

A question an engineer would ask, through the model's own chat template (system turn included), prompt
batched eight positions a pass (FIFO card reads, the measured faster way), then a few answer tokens. The run
gives the two numbers a user sees: time to the first answer token, and seconds per token after it."""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from chat_template import escape, render  # noqa: E402

QUESTION = "What is the difference between SPI and I2C? Answer in two sentences."


def main():
    lines = ["# psram_llm realistic use -- GENERATED by make_tests_realistic.py; edit that, not this.",
             "::sdio fifo",
             "::prefill 1",
             "chat_spi_i2c | 4 | %s" % escape(render(QUESTION))]
    with open(os.path.join(HERE, "tests_realistic.txt"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("tests_realistic.txt: %d lines" % len(lines))


if __name__ == "__main__":
    main()
