#!/usr/bin/env python3
"""make_tests_night2.py -- write tests_night2.txt, chat prompts rendered by the model's own template.

    python make_tests_night2.py

Chat prompts are one board line each: chat_template.render() then escape(), so the board's unescape gives
back exactly the string the template produced. Hand-escaping those strings is how the pre-2026-09-27 files
came to leave out the template's system turn."""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from chat_template import escape, render  # noqa: E402

GEN = 16
PLAIN = [("france", "The capital of France is"),
         ("arith", "Q: What is 17 + 25?\nA:"),
         ("fib", "def fibonacci(n):\n"),
         ("js", "const add = (a, b) =>")]
CHAT = [("colors", "Name three primary colors."),
        ("french", 'Translate "good morning" into French.'),
        ("reverse", "Write a Python one-liner that reverses a list called xs."),
        ("psram", "What does PSRAM stand for?")]

HEAD = """# psram_llm v5 suite -- GENERATED by make_tests_night2.py; edit that, not this.
# Run by suite.py in ROUNDS: run 1 of everything, then run 2, then run 3.
#   id | tokens to generate | prompt        (\\n = newline, the board unescapes \\n \\t \\\\)
#   @multi <id> | <tokens> ... @end        prompts answered TOGETHER (::multi): one pass over the weights
#                                           feeds every unfinished prompt; lines are  id | prompt
#
# France is run three ways, and all three must print the same tokens AND the same logits to the last
# digit, because each is the same arithmetic on the same machine in the same order:
#   france      prompt batched through tl_prefill (1 pass for its 5 tokens), then one token per pass
#   france_tok  every position one pass (tl_forward), the path run 2 measured at 127.7 s a pass
#   together8.france   the same prompt inside an 8-prompt group (tl_step with 1..8 slots a pass)
# Chat prompts are the model's own template (system turn included), rendered by chat_template.py.
#
# Smallest top-2 logit margin of the PC reference over each prompt's first 16 tokens (survey
# bench-archive/20260927-060624-psram_llm-survey). The board's logits drift up to ~0.11 from the PC's
# (run 2), so a divergence where the margin is smaller is a near tie the board may legitimately take the
# other way, and anywhere else a fault:
#   france 0.006 (gen step 10; run 2 matched through it)   arith 0.631   fib 0.788   js 1.059
#   colors 0.0996 (gen step 1; kept on purpose as a near-tie probe)   french 0.746   reverse 0.268   psram 0.143
# Projected from run 2's split (not measured): france 17 passes ~38 min, france_tok 21 passes ~45 min,
# together8 48 passes for 283 positions ~3.6 h (one at a time: 128 passes, ~5.8 h). About 4.8 h a round.
"""


def main():
    lines = [HEAD.rstrip("\n"),
             "::prefill 1",
             "france | %d | The capital of France is" % GEN,
             "::prefill 0",
             "france_tok | %d | The capital of France is" % GEN,
             "::prefill 1",
             "@multi together8 | %d" % GEN]
    lines += ["%s | %s" % (i, escape(p)) for i, p in PLAIN]
    lines += ["%s | %s" % (i, escape(render(u))) for i, u in CHAT]
    lines.append("@end")
    with open(os.path.join(HERE, "tests_night2.txt"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("tests_night2.txt: %d lines" % len(lines))


if __name__ == "__main__":
    main()
